name: Issue Management

on:
  issues:
    types: [opened, edited, closed, reopened, assigned, unassigned]
  issue_comment:
    types: [created]

jobs:
  triage:
    name: Issue Triage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Initial Triage
        if: github.event.action == 'opened'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;

            // Add default labels based on title/body content
            const labels = [];
            const title = issue.title.toLowerCase();
            const body = issue.body.toLowerCase();

            if (title.includes('bug') || body.includes('bug')) {
              labels.push('bug');
            }
            if (title.includes('feature') || body.includes('feature')) {
              labels.push('enhancement');
            }
            if (title.includes('documentation') || body.includes('documentation')) {
              labels.push('documentation');
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: labels
              });
            }

            // Add welcome comment for new contributors
            const creator = issue.user.login;
            const contributors = await github.rest.repos.listContributors({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const isNewContributor = !contributors.data.some(c => c.login === creator);

            if (isNewContributor) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `Thanks for opening your first issue @${creator}! The team will review it soon. 🙌`
              });
            }

  notify:
    name: Notify Team
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'reopened'

    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "issues"
          slack-message: "New issue opened: ${{ github.event.issue.title }} (${{ github.event.issue.html_url }})"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
